# Generated by Django 3.1.7 on 2021-03-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='opened', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(),
        ),
    ]
